# fly.toml app configuration file generated for datingapp--an on 2023-11-21T16:05:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingapp--an"
primary_region = "otp"

[build]
  image = "anovak57/datingapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__ApiKey = "544223977179513"
  CloudinarySettings__CloudName = "dxa0oghzc"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.ports]
    handlers = ["http"]
    port = 80

  [services.ports]
    handlers = ["http"]
    port = 443

  [services.ports]
    handlers = ["tls", "http"]
    port = 443

  [services.ports]
    handlers = ["websockets"]
    port = 443
    proto = "tcp"

  [[services.ports.routes]]
    src = "/hubs/message"
    dst = 8080

